### ISSUE TITLE
Fix View of Public Devices

### ISSUE THREAD

**Issue by BiancaWentzel** [MPIB/Lagerregal#175]
The container, breadcrumbs-bar and footer is missing

**Comment by BiancaWentzel** [comment]
I found the error! The {% endif %} was located at the wrong spot (after <div class="container"></div>) -> has to be located before <div class="container></div> (base.html)

**Comment by octomike** [comment]
Awesome, can you PR? :)

**Comment by octomike** [comment]
fixed with #177
