### ISSUE TITLE
Mark device as returned - bug

### ISSUE THREAD

**Issue by amaddio** [MPIB/Lagerregal#179]
When I use the "Mark device as returned" button for a device. It does not set the room to its origin value. A user has to also change the room number to its origin value by clicking the "edit" button of the device and then assign the room manually. That feels like a bug to me unless the behaviour is supposed to be like that.

**Comment by octomike** [comment]
Very true, will be fixed asap.

**Comment by amaddio** [comment]
Ah great. Happy to hear 👏

**Comment by amaddio** [comment]
Thanks very much 👍 . Just tested it. Works now as expected.

**Comment by octomike** [comment]
Thanks for the report, keep 'em coming! :smile:
