### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by octomike** [MPIB/Lagerregal#181]
I want to use bootstrap 4 so we can include the new fancy [bootswatch](https://bootswatch.com/) themes :)

Necessary tasks:

+ replace all bootstrap related css/js with v4 equivalents
+ replace all current bootswatch themes with newer equivalents
+ go through the [bootstrap migration list](https://v4-alpha.getbootstrap.com/migration/) and change *all* elements according to their migration notes

**Comment by xi** [comment]
The first two points get much simpler with #283.

But there is another issue: The "paper" theme has been renamed to "materia" ([related blog post](http://blog.bootswatch.com/post/167233472837/bootswatch-4-plus-five-new-themes)). We probably need to write a [custom migration like the one I did](https://github.com/MPIB/Lagerregal/pull/283/commits/6562a074abbf35b8cc584cf65482ad9cc7266f55#diff-77d545b400b41234fba9e25f14284ace).
