### ISSUE TITLE
Add lending history (of devices) for a particular user

### ISSUE THREAD

**Issue by philjak** [MPIB/Lagerregal#188]
Hi,

currently it's possible to see a lending history (of users) for a particular device. 

It'd be an awesome feature to have a lending history (of devices) for a particular user.

Thanks!
Philip

**Comment by octomike** [comment]
Awesome idea.

I was thinking about a new tab in the user's view or a new paragraph in the device tab , which basically lists:

```python
Lending.objects.filter(owner__username=user).order_by('-lenddate')
```
in some nice way. Maybe grouped by device id with a [media list](https://getbootstrap.com/docs/3.3/components/#media-default) and the device image. Needs special care for devices that are gone and devices that haven't been returned yet.
