### ISSUE TITLE
Combine login_required and premission_required

### ISSUE THREAD

**Issue by LizzAlice** [MPIB/Lagerregal#214]
if logged in and no permission: 403; if not logged in: redirect to login 
maybe with django-braces?

**Comment by xi** [comment]
This is what the [django docs](https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.decorators.permission_required) say about this:

> `permission_required(perm, login_url=None, raise_exception=False)`
>
> […]
>
> If the `raise_exception` parameter is given, the decorator will raise `PermissionDenied`, prompting the 403 (HTTP Forbidden) view instead of redirecting to the login page.
>
> If you want to use raise_exception but also give your users a chance to login first, you can add the login_required() decorator:
>
> ```
> from django.contrib.auth.decorators import login_required, permission_required
>
> @login_required
> @permission_required('polls.can_vote', raise_exception=True)
> def my_view(request):
>     …
> ```

**Comment by LizzAlice** [comment]
- []

**Comment by xi** [comment]
This is not fully fixed with #293 as some views still use the 3rd party `permission_required` decorator.
