### ISSUE TITLE
Update to django 2.0

### ISSUE THREAD

**Issue by xi** [MPIB/Lagerregal#228]
See also https://docs.djangoproject.com/en/2.0/releases/2.0/

What needs to be done (may be incomplete):

- before update
  - [X] python3 compatibility
  - [X] Make sure all ForeignKey fields have `on_delete` set
  - [X] import from `django.urls` instead of `django.core.urlresolvers`
  - [X] change `MIDDLEWARE_CLASSES` to `MIDDELWARE`
  - [X] replace `django.template.loaders.eggs.Loader`
  - [X] change `user.is_authenticated()` to `user.is_authenticated`
- after update
  - [ ] change url definitions to use `path()`
  - [ ] use builtin `view` permissions instead of own `read` (2.1)

**Comment by xi** [comment]
I think @LizzAlice has already worked on adding `on_delete`, but I cannot find the branch anymore. Anyone knows where it went?

**Comment by LizzAlice** [comment]
Have I? I can't remember creating a branch for that, maybe I changed one ore two of them while doing something else?

**Comment by xi** [comment]
django 2.1 also brings the "view" permissions which can replace our own "read" permissions.
