### ISSUE TITLE
Email Template Recipient prefill broken

### ISSUE THREAD

**Issue by octomike** [MPIB/Lagerregal#302]
On editing a device or on creating new devices in `device_form.html` the corresponding template gets picked, but the default recipients for the template aren't added.

**Comment by xi** [comment]
I don't really know what this is about. Can you give more context?

**Comment by xi** [comment]
reopening because the reference in #306 was wrong

**Comment by xi** [comment]
So far `MailTemplate.default_recipients` is ignored when recipients are provided explicitly (e.g. device update). From this issue I understand that it is desired to extend the list of recipients instead of replacing it. That's what I did in f6eb7142f9b1e85b05d7548078f90a8159ab94af.
